- src/GeneratesUuid.php
> Fix docblocks.

- .editorconfig
- .gitattributes
> Add dotfiles.

- tests/feature/UuidTest.php
- tests/unit/UuidResolversTest.php
> Use stricter assertions.

- composer.json
Use pretty print for composer.json.
> Use pretty print for composer.json.

- .travis.yml
Add composer cache and travis retry.
> Add composer cache and travis retry.

- tests/Post.php
- tests/UncastPost.php
- tests/unit/UuidResolversTest.php
> Remove useless imports.

- tests/unit/UuidResolversTest.php
Use a data-provider for tests.
> Use a data-provider for tests.

- .gitattributes
- .styleci.yml
Enable StyleCI.
---
Note:
This repository needs to be enabled in https://styleci.io/ first @michaeldyrynda
> Enable StyleCI.

- tests/Feature/UuidTest.php
- tests/Unit/UuidResolversTest.php
> Let the tests respect PSR-4

- src/GeneratesUuid.php
> Dry up code

- src/GeneratesUuid.php
> use a stricter comparison

- tests/Feature/UuidTest.php
- tests/Fixtures/Model.php
- tests/Fixtures/Post.php
- tests/Fixtures/UncastPost.php
- tests/UncastPost.php
> Move test models to fixtures

- .travis.yml
- composer.json
Let laravel-model-uuid support Illuminate 5.2
> Let laravel-model-uuid support Illuminate 5.2

- composer.json
- Re-organize composer sections
- Use recent OR syntax
- Fix type
- Add suggested package version
- Add keywords
- Add config options
---
With these keywords, this package will also be referenced in https://packalyst.com/
> Re-organize Composer.json

- src/GeneratesUuid.php
> Add variable type-hinting

- src/GeneratesUuid.php
Add class variable type hinting
> Add class variable type hinting

- src/GeneratesUuid.php
No need to generate resolving function
> No need to generate resolving function

- tests/Feature/UuidTest.php
> Factorize tests UUIDs.

- README.md
Add version-eye dependency status.
> Add version-eye dependency status.

- README.md
> Add some readme adjustements.

- tests/Unit/UuidResolversTest.php
Remove useless testcase setup.
> Remove useless testcase setup.

- tests/Unit/UuidResolversTest.php
> Use Testcase namespace

- src/GeneratesUuid.php
- tests/Feature/UuidTest.php
- tests/Fixtures/MultipleUuidPost.php
This solves the https://github.com/michaeldyrynda/laravel-model-uuid/issues/58
> Allow Multiple uuids in the same table

- .github/workflows/run-tests.yml
- composer.json
> Add support for PHP 8

- README.md
- composer.json
- src/Casts/EfficientUuid.php
- src/Exceptions/UnknownGrammarClass.php
- src/LaravelModelUuidServiceProvider.php
- src/Rules/EfficientUuidExists.php
- tests/Feature/DatabaseInvalidSchemaGrammarTest.php
- tests/Feature/DatabaseMySqlSchemaGrammarTest.php
- tests/Feature/DatabasePostgresSchemaGrammarTest.php
- tests/Feature/DatabaseSQLiteSchemaGrammarTest.php
- tests/Feature/EfficientUuidExistsRuleTest.php
- tests/Feature/UuidTest.php
- tests/Fixtures/EfficientUuidPost.php
- tests/TestCase.php
This PR combines [laravel-efficient-uuid](https://github.com/michaeldyrynda/laravel-efficient-uuid) and this repo into one package, simplifying maintenance and testing.
`dyrynda/laravel-efficient-uuid` has been marked abandoned, suggesting use of this package.
> Feature: Migrate efficient UUID support
